name: Run Telegram Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot
        pip install python-dotenv  # Optional but recommended

    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Use GitHub Secrets for security
      run: python bot.py